
from enum import Enum
class Action(Enum):
    TURN_LEFT = 1
    TURN_RIGHT = 2
    TURN_UP = 3
    TURN_DOWN = 4
    MOVE_FORWARD = 5
    GRAB_GOLD = 6 #
    PERCEIVE_BREEZE = 7 #
    PERCEIVE_STENCH = 8 #
    SHOOT = 9 #
    KILL_WUMPUS = 10 #
    KILL_NO_WUMPUS = 11
    BE_EATEN_BY_WUMPUS = 12 #
    FALL_INTO_PIT = 13 #
    KILL_ALL_WUMPUS_AND_GRAB_ALL_FOOD = 14
    CLIMB_OUT_OF_THE_CAVE = 15
    DECTECT_PIT = 16 #
    DETECT_WUMPUS = 17 #
    DETECT_NO_PIT = 18
    DETECT_NO_WUMPUS = 19
    INFER_PIT = 20 #
    INFER_NOT_PIT = 21#
    INFER_WUMPUS = 22 #
    INFER_NOT_WUMPUS = 23
    DETECT_SAFE = 24
    INFER_SAFE = 25