from enum import Enum

class Action(Enum):
    TURN_LEFT = 1
    TURN_RIGHT = 2
    TURN_UP = 3
    TURN_DOWN = 4
    GO_STRAIGHT = 5
    GET_GOLD = 6
    PERCEIVE_BREEZE = 7
    SMELL_STENCH = 8
    SHOOT = 9
    KILL_WUMPUS = 10
    WUMPUS_NOT_KILLED = 11
    EATEN_BY_WUMPUS = 12
    FALL_IN_HOLE = 13
    KILL_ALL_WUMPUS_AND_GRAB_ALL_GOLD = 14
    ESCAPE_FROM_THE_CAVE = 15
    FIND_HOLE = 16
    FIND_WUMPUS = 17
    HOLE_NOT_FOUND = 18
    WUMPUS_NOT_FOUND = 19
    INFER_HOLE = 20
    HOLE_NOT_INFERRED = 21
    INFER_WUMPUS = 22 
    WUMPUS_NOT_INFERRED = 23
    SAFE_FOUND = 24
    INFER_SAFE = 25